-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 22:11:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- Insertar datos en la tabla Administrador
INSERT INTO Administrador (Nom_usuario, Clave_usuario, Rol, Apellido)
VALUES ('Alejandro', 123456789, 'Adm', 'Martinez');

-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `ID_adm` INT NOT NULL,
  `Nom_usuario` VARCHAR(11) NOT NULL,
  `Clave_usuario` INT NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_adm`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_adm_UNIQUE` ON `mydb`.`Administrador` (`ID_adm` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nom_usuario_UNIQUE` ON `mydb`.`Administrador` (`Nom_usuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `Apellido_UNIQUE` ON `mydb`.`Administrador` (`Apellido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria_pelicula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_pelicula` (
  `ID_categoria` INT NOT NULL,
  `Nom_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pelicula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pelicula` (
  `ID_pelicula` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Trama` VARCHAR(45) NOT NULL,
  `ID_categoria` INT NOT NULL,
  `Publico` INT NOT NULL,
  `Origen` VARCHAR(45) NOT NULL,
  `Duracion` INT NOT NULL,
  `Idioma` VARCHAR(45) NOT NULL,
  `Director` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  `Adm` INT NOT NULL,
  CONSTRAINT `ID_categoria`
    FOREIGN KEY (`ID_pelicula`)
    REFERENCES `mydb`.`Categoria_pelicula` (`ID_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Adm`
    FOREIGN KEY (`Adm`)
    REFERENCES `mydb`.`Administrador` (`ID_adm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Adm_idx` ON `mydb`.`Pelicula` (`Adm` ASC) VISIBLE;

CREATE INDEX `ID_categoria_idx` ON `mydb`.`Pelicula` (`ID_pelicula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Proyeccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyeccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyeccion` (
  `ID_proyeccion` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Horario` INT NOT NULL,
  `ID_pelicula` INT NULL,
  PRIMARY KEY (`ID_proyeccion`),
  CONSTRAINT `ID_pelicula`
    FOREIGN KEY (`ID_pelicula`)
    REFERENCES `mydb`.`Pelicula` (`ID_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_pelicula_idx` ON `mydb`.`Proyeccion` (`ID_pelicula` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
